{title: "Surgeon", iq: 234.1},
{title: "Physician", iq: 161.1},
{title: "Corporate executive", iq: 148.0},
{title: "Psychiatrist", iq: 147.7},
{title: "Dentist", iq: 140.0},
{title: "Orthodontist", iq: 131.2},
{title: "Podiatrist", iq: 129.1},
{title: "Judge", iq: 127.9},
{title: "Attorney", iq: 127.8},
{title: "Petroleum engineer", iq: 126.1},
{title: "Pharmacist", iq: 126.1},
{title: "Physicist", iq: 124.9},
{title: "Commercial airline pilot", iq: 124.9},
{title: "Astronomer", iq: 124.5},
{title: "Financial planner", iq: 122.8},
{title: "Nuclear engineer", iq: 121.1},
{title: "Optometrist", iq: 120.7},
{title: "Aerospace engineer", iq: 120.2},
{title: "Mathematician", iq: 119.8},
{title: "Public relations executive", iq: 118.1},
{title: "Economist", iq: 116.9},
{title: "Actuary", iq: 116.9},
{title: "Software engineer", iq: 116.9},
{title: "Meteorologist", iq: 116.0},
{title: "School principal", iq: 116.0},
{title: "Physician assistant", iq: 115.6},
{title: "Electrical engineer", iq: 115.2},
{title: "Web developer", iq: 115.2},
{title: "Construction foreman", iq: 114.8},
{title: "Geologist", iq: 114.4},
{title: "Veterinarian", iq: 114.4},
{title: "Computer systems analyst", iq: 112.7},
{title: "Mechanical engineer", iq: 112.6},
{title: "Civil engineer", iq: 112.2},
{title: "Industrial engineer", iq: 111.8},
{title: "Biologist", iq: 111.4},
{title: "Physical therapist", iq: 111.4},
{title: "Statistician", iq: 111.0},
{title: "Architect", iq: 111.0},
{title: "Computer programmer", iq: 110.1},
{title: "Occupational therapist", iq: 109.7},
{title: "Sociologist", iq: 109.7},
{title: "Chiropractor", iq: 108.9},
{title: "Chemist", iq: 108.9},
{title: "Stockbroker", iq: 108.6},
{title: "Dental hygienist", iq: 108.4},
{title: "Psychologist", iq: 108.0},
{title: "Speech pathologist", iq: 107.6},
{title: "Registered nurse", iq: 107.2},
{title: "Historian", iq: 106.8},
{title: "Technical writer", iq: 106.8},
{title: "Occupational safety/health inspector", iq: 106.7},
{title: "Audiologist", iq: 106.7},
{title: "Market research analyst", iq: 106.4},
{title: "Advertising account executive", iq: 106.3},
{title: "Fashion designer", iq: 106.0},
{title: "Philosopher", iq: 105.9},
{title: "Accountant", iq: 105.5},
{title: "Farmer", iq: 105.1},
{title: "Industrial designer", iq: 104.7},
{title: "Insurance underwriter", iq: 104.7},
{title: "Telephone installer and repairer", iq: 104.6},
{title: "Zoologist", iq: 104.2},
{title: "Communications equipment mechanic", iq: 103.8},
{title: "Loan officer", iq: 103.4},
{title: "Purchasing agent", iq: 103.4},
{title: "Engineering technician", iq: 103.4},
{title: "Medical technologist", iq: 103.4},
{title: "Author", iq: 103.0},
{title: "Undertaker", iq: 103.0},
{title: "Librarian", iq: 103.0},
{title: "Surveyor", iq: 103.0},
{title: "Railroad conductor", iq: 103.0},
{title: "Conservationist", iq: 102.9},
{title: "Anthropologist", iq: 102.5},
{title: "Vocational counselor", iq: 102.5},
{title: "Highway patrol officer", iq: 102.5},
{title: "Aircraft mechanic", iq: 102.5},
{title: "Respiratory therapist", iq: 102.5},
{title: "Dietitian", iq: 102.1},
{title: "Mail carrier", iq: 102.1},
{title: "Motion picture editor", iq: 101.8},
{title: "Sales representative", iq: 101.8},
{title: "Publication editor", iq: 101.7},
{title: "Archeologist", iq: 101.7},
{title: "Physiologist", iq: 101.7},
{title: "Stationary engineer", iq: 101.7},
{title: "Teacher", iq: 101.7},
{title: "Electrical equipment repairer", iq: 101.7},
{title: "Newscaster", iq: 101.4},
{title: "Tax examiner", iq: 100.9},
{title: "Buyer", iq: 100.9},
{title: "Police officer", iq: 100.9},
{title: "Actor", iq: 100.8},
{title: "Stenographer", iq: 100.5},
{title: "Museum curator", iq: 100.5},
{title: "Electrician", iq: 100.0},
{title: "Bricklayer", iq: 100.0},
{title: "Parole officer", iq: 100.0},
{title: "Paralegal assistant", iq: 100.0},
{title: "Tool-and-die maker", iq: 100.0},
{title: "Insurance agent", iq: 99.7},
{title: "Personnel recruiter", iq: 99.6},
{title: "Hotel manager", iq: 99.6},
{title: "Plumber", iq: 99.6},
{title: "Architectural drafter", iq: 99.6},
{title: "Firefighter", iq: 99.2},
{title: "Set designer", iq: 99.2},
{title: "Artist (fine art)", iq: 98.8},
{title: "Industrial machine repairer", iq: 98.7},
{title: "Advertising salesperson", iq: 98.4},
{title: "Clergy", iq: 98.4},
{title: "Sheet metal worker", iq: 97.5},
{title: "Heating and refrigeration mechanic", iq: 97.5},
{title: "Real estate agent", iq: 97.1},
{title: "Photojournalist", iq: 97.1},
{title: "Flight attendant", iq: 97.1},
{title: "Construction machinery operator", iq: 97.1},
{title: "Social worker", iq: 97.1},
{title: "Sewage plant operator", iq: 97.1},
{title: "Licensed practical nurse", iq: 97.0},
{title: "Stevedore", iq: 96.6},
{title: "Carpenter", iq: 96.6},
{title: "Corrections officer", iq: 96.6},
{title: "Choreographer", iq: 96.3},
{title: "Automobile body repairer", iq: 96.2},
{title: "Plasterer", iq: 96.2},
{title: "Office machine repairer", iq: 96.2},
{title: "Machinist", iq: 96.2},
{title: "Truck driver", iq: 96.2},
{title: "Carpet and tile installer", iq: 95.8},
{title: "Drywall applicator and finisher", iq: 95.8},
{title: "Computer service technician", iq: 95.8},
{title: "Nuclear decontamination technician", iq: 95.8},
{title: "Glazier", iq: 95.4},
{title: "Sailor", iq: 95.4},
{title: "Medical laboratory technician", iq: 95.4},
{title: "Automobile mechanic", iq: 95.0},
{title: "Dental laboratory technician", iq: 95.0},
{title: "Welder", iq: 94.9},
{title: "Newspaper reporter", iq: 94.6},
{title: "Jeweler", iq: 94.5},
{title: "Meter reader", iq: 94.5},
{title: "Roofer", iq: 94.5},
{title: "Bus driver", iq: 94.5},
{title: "Appliance repairer", iq: 94.5},
{title: "Painter", iq: 94.5},
{title: "Agricultural scientist", iq: 94.5},
{title: "Ironworker", iq: 94.5},
{title: "Machine tool operator", iq: 94.5},
{title: "Broadcast technician", iq: 94.2},
{title: "Piano tuner", iq: 94.1},
{title: "Musical instrument repairer", iq: 94.1},
{title: "Compositor/typesetter", iq: 94.1},
{title: "Optician", iq: 94.1},
{title: "Bookkeeper", iq: 94.1},
{title: "Typist", iq: 94.1},
{title: "Electrical technician", iq: 94.0},
{title: "Garbage collector", iq: 93.7},
{title: "Roustabout", iq: 93.7},
{title: "Dairy farmer", iq: 93.7},
{title: "Lumberjack", iq: 93.7},
{title: "Bookbinder", iq: 93.3},
{title: "Telephone operator", iq: 93.3},
{title: "Medical records technician", iq: 93.3},
{title: "Travel agent", iq: 93.3},
{title: "Drill-press operator", iq: 93.3},
{title: "Photographer", iq: 92.9},
{title: "Emergency medical technician", iq: 92.8},
{title: "Vending machine repairer", iq: 92.8},
{title: "Furniture upholsterer", iq: 92.8},
{title: "Forklift operator", iq: 92.8},
{title: "Medical secretary", iq: 92.8},
{title: "Construction worker", iq: 92.4},
{title: "Butcher", iq: 92.4},
{title: "Disc jockey", iq: 92.1},
{title: "Precision assembler", iq: 92.0},
{title: "Shipping and receiving clerk", iq: 92.0},
{title: "Automobile assembler", iq: 91.6},
{title: "Dressmaker", iq: 91.6},
{title: "Photographic process worker", iq: 91.2},
{title: "Receptionist", iq: 90.7},
{title: "Barber", iq: 90.3},
{title: "Guard", iq: 90.3},
{title: "Nurse’s aid", iq: 90.3},
{title: "Bank teller", iq: 90.3},
{title: "Cosmetologist", iq: 89.9},
{title: "Teacher’s aide", iq: 89.9},
{title: "Shoe maker and repairer", iq: 89.9},
{title: "Recreation worker", iq: 89.5},
{title: "Janitor", iq: 89.5},
{title: "Chauffeur", iq: 89.5},
{title: "Taxi driver", iq: 89.0},
{title: "Retail salesman", iq: 88.6},
{title: "Child care worker", iq: 88.2},
{title: "Maid", iq: 88.2},
{title: "Bartender", iq: 87.8},
{title: "Waiter", iq: 87.8},
{title: "Cashier", iq: 87.7},
{title: "Dishwasher", iq: 87.7},
